### ISSUE TITLE
Guide "finish" not Working

### ISSUE THREAD

**Issue by wbejarano** [OpenLiberty/guide-maven-multimodules#38] opened 2019-04-02 22:38 UTC
[INFO] Reactor Summary for io.openliberty.guides.multimodules.modules 0.0.1-SNAPSHOT:
[INFO]
[INFO] io.openliberty.guides.multimodules.modules ......... FAILURE [  3.139 s]
[INFO] io.openliberty.guides.multimodules.jar ............. SKIPPED
[INFO] io.openliberty.guides.multimodules.war ............. SKIPPED
[INFO] io.openliberty.guides.multimodules.ear ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.593 s
[INFO] Finished at: 2019-04-02T17:24:54-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.6.4:start-server (default-cli) on project io.openliberty.guides.multimodules.modules: java.util.zip.ZipException: archive is not a ZIP archive -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by gkwan-ibm** [comment] 2019-04-03 14:15
hi @wbejarano , would you tell us more information how you got this problem? I cannot reproduce it on my Mac.
1. Which version of maven and JDK were used? And which platform? (output of `mvn -version` should have those information)
1. Did you run the `mvn install` under the finish directory? Or somewhere?
1. Did you run other guides before? And which?

**Comment by wbejarano** [comment] 2019-04-03 14:43
Hello @gkwan-ibm, I ran that with:

1. version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T13:41:47-05:00)
Maven home: C:\others\apache-maven-3.6.0\bin\..
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

2. Yeah, I ran `mvn install`  under finish directory, and into jar, war and ear directory too.
3. No, I didn't

**Comment by justineechen** [comment] 2019-04-03 20:47
Hi @wbejarano,
I wasn't able to reproduce your issue on Windows 10, Java version 1.8.0_201 / Oracle. On my path: C:\Program Files\Java\jdk1.8.0_201\bin. 

Could you try the following:
1. Run `mvn clean` in finish
2. Run `mvn install > install.out 2>&1` (redirects all system err/out into install.out)
3. Send us the file `install.out`

Thanks!
Justine

**Comment by wbejarano** [comment] 2019-04-03 20:59
Hello @justineechen 
It is the file
[install.out.txt](https://github.com/OpenLiberty/guide-maven-multimodules/files/3040723/install.out.txt)

Thks!

**Comment by justineechen** [comment] 2019-04-05 17:57
Hi @wbejarano!
It looks like your original output looks different from the one you sent us in `install.out.txt`, did you do anything different this time or between the builds?

Also, could you run `netstat -aon | find /i “9080”` to see if there is something running on port 9080 already? That could potentially be your issue.

Thanks, 
Justine

**Comment by justineechen** [comment] 2019-04-08 14:37
Hi @wbejarano, did you try seeing if the port was in use? Please let us know if your issue is persisting.
Thank you!
Justine

**Comment by wbejarano** [comment] 2019-04-09 17:00
Hi @justineechen 
I was trying to run everything from new clone, and now it have a new problem. I attach files.
[install.out.txt](https://github.com/OpenLiberty/guide-maven-multimodules/files/3060142/install.out.txt)
[start_server.out.txt](https://github.com/OpenLiberty/guide-maven-multimodules/files/3060143/start_server.out.txt)

**Comment by justineechen** [comment] 2019-04-09 17:03
Hi @wbejarano, did you run `mvn liberty:start-server`? It looks like maybe you did `start_server`

**Comment by wbejarano** [comment] 2019-04-09 17:50
Hi @justineechen you are right. 
I attach again 
[start_server.out.txt](https://github.com/OpenLiberty/guide-maven-multimodules/files/3060310/start_server.out.txt)
[netstat.out.txt](https://github.com/OpenLiberty/guide-maven-multimodules/files/3060311/netstat.out.txt)

**Comment by justineechen** [comment] 2019-04-10 15:08
Hi @wbejarano! It looks like you may have a corrupted jar in your ~/.m2 folder. So could you try clearing your maven cache by running `rm -rf ~/.m2` and running `mvn install` and then `mvn liberty:start-server` again?

**Comment by wbejarano** [comment] 2019-04-10 15:41
Hi @justineechen 

I cleaned '.m2' folder and run 'mvn install' and 'mvn liberty:start-server' too, and all run Ok.

[INFO] --- maven-failsafe-plugin:3.0.0-M1:integration-test (integration-test) @ io.openliberty.guides.multimodules.ear ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.io.openliberty.guides.multimodules.Test
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.554 s - in it.io.openliberty.guides.multimodules.Test
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- liberty-maven-plugin:2.6.4:test-stop-server (test-stop-server) @ io.openliberty.guides.multimodules.ear ---

Thks for all!

**Comment by justineechen** [comment] 2019-04-10 17:37
I'm glad I could help @wbejarano, I will close this issue then, thanks!

**Closed by justineechen** 2019-04-10 17:37 UTC
Labels: L3
